class Variable:
    read_lock = 'Shared/read'
    status_lock = 'Shared/status'
    used_lock = 'Shared/used'
    alive_lock = 'Shared/alive'
    status_filepath = 'Shared/status.txt'
    used_filepath = 'Shared/used.txt'
    alive_filepath = 'Shared/alive.txt'
    model_dir = 'Models/'
    history_dir = 'History/'
    alive = '1'
    dead = '11'
